export const enum PermissionKey {
  dashboard = "view_dashboard",
  companyDashboard = "view_companyDashboard",
  schedules = "view_schedules",
  users = "view_users",
  roles = "view_roles",
  companies = "view_companies",
  deviceTypes = "view_deviceTypes",
  regions = "view_regions",
  segments = "view_segments",
  checklistCategories = "view_checklistCategories",
  checklists = "view_checklists",
  units = "view_units",
  serviceUsers = "view_serviceUsers",
  services = "view_services",
  damages = "view_damages",
  emergencies = "view_emergencies",
  customers = "view_customers",
  deals = "view_deals",
  financials = "view_financials",
  dealsArchive = "view_dealsArchive",
  liftFieldCategories = "view_liftFieldCategories",
  liftFields = "view_liftFields",
  dealPlaceholders = "view_dealPlaceholders",
  messageTemplates = "view_messageTemplates",
  companyMessageTemplates = "view_companyMessageTemplates"
}
